# Generated by Django 4.2 on 2023-07-07 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Won', 'Won'), ('Draw', 'Draw')], default='Ongoing', max_length=8)),
                ('winner', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=255)),
                ('player2', models.CharField(max_length=255)),
                ('board', models.CharField(default='000000000000000000000000000000000000000000', max_length=255)),
                ('turn', models.CharField(default='player1', max_length=255)),
                ('last_move', models.IntegerField(default=-1)),
                ('last_move_player', models.CharField(default='player2', max_length=255)),
                ('last_move_time', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectFour.game')),
            ],
        ),
    ]
