# Generated by Django 4.2 on 2023-07-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectFour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='board',
        ),
        migrations.AlterField(
            model_name='move',
            name='last_move_player',
            field=models.CharField(default='player1', max_length=255),
        ),
    ]
